"""Shared constants mirroring the Turbo Pascal definitions."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List

# Variable group offsets replicate DATA_RSC.PAS
GRNAM0 = 0
GCNAM0 = 20
STNAM0 = 50
SCNAM0 = 100
GMXNAM0 = 150
SMXNAM0 = 175
GACNAM0 = 200
SACNAM0 = 225
MIXNAM0 = 235
FORMNAME = 255

VFUNC_NAMES: List[str] = ["", "MX", "mn", "Avg", "Abs", "AMX"]

'''
Createas a lookup table so we can map the numeric IDs to the variable names.
This creates a dictionary where:
1) Keys are integers (the variable IDs)
2) Values are strings (the variable names)

The dictionary is created using dictionary comprehension.
The ** operator is used to merge multiple dictionaries.
The enumerate function is used to generate the variable IDs.
The variable IDs are generated by adding 1 to the group offset and the index.
The variable names are generated by the name of the variable.

ex. if we have GRNAM0 = 0 and the list ["XVEL", "YVEL", "S11"], the dictionary will be: {1: "XVEL", 2: "YVEL", 3: "S11"}
'''
_VAR_TABLE: Dict[int, str] = {
    **{GRNAM0 + i + 1: name for i, name in enumerate([
        "XVEL", "YVEL", "S11", "S22", "S12", "ZVEL", "S33", "S23", "S31", "S31",
    ])},
    **{GCNAM0 + i + 1: name for i, name in enumerate([
        "DIL", "V-abs", "TauMx", "Sig-3", "Sig-1", "Sig-2", "M-Ang1", "ESS", "DEV",
        "aXVEL", "aYVEL", "aS12", "aZVEL", "aS23", "aS31", "aS31", "S.E.", "K.E.",
        "T.E.", "Fail", "e-plas",
    ])},
    **{STNAM0 + i + 1: name for i, name in enumerate([
        "t11_s1", "t11_s0", "t1v_s1", "t1v_s0", "t1sh", "t1d-r",
        "nvel-r", "ndis-r", "Sh-bnd", "T1slip", "TaSlip", "N-bnd",
        "t22_s1", "t22_s0", "t2v_s1", "t2v_s0", "t1t2s1",
        "t1t2s0", "t2sh", "t2d-r", "T2slip",
    ])},
    **{SCNAM0 + i + 1: name for i, name in enumerate([
        "nd-s1", "nd-s0", "Tad-r", "t1d_s1", "t1d_s0", "t2d_s1", "t2d_s0",
        "stv_s1", "stv_s0", "sts_s1", "sts_s0",
    ])},
    **{GMXNAM0 + i + 1: name for i, name in enumerate(["MaxVel"])},
    **{SMXNAM0 + i + 1: name for i, name in enumerate([
        "nv-mx", "nd-mx", "t1v-mx", "t1d-mx", "t2v-mx", "t2d-mx", "t11-mx", "t22-mx",
    ])},
    **{GACNAM0 + i + 1: name for i, name in enumerate(["Xdisp", "Ydisp", "Zdisp"])},
    **{SACNAM0 + i + 1: name for i, name in enumerate([""])},
    **{MIXNAM0 + i + 1: name for i, name in enumerate(["skn", "sks", "sNs", "sSs"])},
    FORMNAME: "Form",
}


def var_name(vnum: int) -> str:
    """Return human readable variable name for a Turbo Pascal variable id."""
    return _VAR_TABLE.get(vnum, f"var{vnum}") if vnum > 0 else ""


def apply_var_split(value: int) -> tuple[int, int]:
    """Split combined Pascal integer into (func_id, var_id)."""
    func_id = value // 0xFFFF
    var_id = value % 0xFFFF
    return func_id, var_id


def func_suffix(func_id: int) -> str:
    """Return suffix for a history/snapshot function index."""
    return VFUNC_NAMES[func_id] if 0 <= func_id < len(VFUNC_NAMES) else ""
